name: Item Randomizer API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test-and-SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 .  --statistics
      - name: Typehint with mypy
        run: |
          mypy .
      - name: Check formatting
        run: black . --exclude=venv --check
      - name: Test with pytest
        run: |
          pytest . -v